import { groth16 } from "snarkjs";

/**
 * Verifies a Zero-Knowledge Proof.
 *
 * @param {string} userId - The user ID to verify against.
 * @param {object} proof - The proof object generated by the ZKP system.
 * @param {object} publicSignals - The public signals corresponding to the proof.
 * @param {string | object} verificationKey - The path to or object containing the verification key.
<<<<<<< HEAD
 * @returns {Promise<boolean>} - True if the proof is valid, false otherwise.
 */
export async function verifyProof(
    userId: string,
    proof: any,
    publicSignals: string[],
    verificationKey: string | object
): Promise<boolean> {
    try {
        // Load the verification key if it's a path
        const key = typeof verificationKey === "string"
            ? await fetch(verificationKey).then((res) => res.json())
            : verificationKey;
=======
 * @returns {boolean} - True if the proof is valid, false otherwise.
 */
export async function verifyProof(
    userId: string,
    proof: object,
    publicSignals: object,
    verificationKey: string | object
): Promise<boolean> {
    try {
        let key;

        if (typeof verificationKey === "string") {
            const response = await fetch(verificationKey);
            if (!response.ok) {
                throw new Error(`Failed to fetch verification key: ${response.status} ${response.statusText}`);
            }
            key = await response.json();
        } else {
            key = verificationKey;
        }
>>>>>>> 3cf583bf0f6db036b5a05e848d654be4292c0d97

        const isValid = await groth16.verify(key, publicSignals, proof);

        console.log(`Proof verification result for user ${userId}:`, isValid);
        return isValid;
    } catch (error: any) {
        console.error("Error verifying ZKP proof:", error.message || error);
        throw new Error("Proof verification failed. Ensure the verification key and inputs are correct.");
    }
}