import { groth16 } from "snarkjs";

/**
 * Verifies a Zero-Knowledge Proof.
 *
 * @param {string} userId - The user ID to verify against.
 * @param {object} proof - The proof object generated by the ZKP system.
 * @param {object} publicSignals - The public signals corresponding to the proof.
 * @param {string} verificationKey - The path to or object containing the verification key.
 * @returns {boolean} - True if the proof is valid, false otherwise.
 */
export async function verifyProof(
    userId: string,
    proof: object,
    publicSignals: object,
    verificationKey: object
    ): Promise<boolean> {
    try {
        // Load the verification key if it's a path
        const key = typeof verificationKey === "string"
        ? await fetch(verificationKey).then((res) => res.json())
        : verificationKey;

        // Verify the proof using the groth16 verifier
        const isValid = await groth16.verify(key, publicSignals, proof);

        console.log(`Proof verification result for user ${userId}:`, isValid);

        return isValid;
    } catch (error) {
        console.error("Error verifying ZKP proof:", error);
        return false;
    }
}
