/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CommitmentStorage {
  export type CommitmentStruct = {
    user: AddressLike;
    commitmentHash: BytesLike;
    timestamp: BigNumberish;
  };

  export type CommitmentStructOutput = [
    user: string,
    commitmentHash: string,
    timestamp: bigint
  ] & { user: string; commitmentHash: string; timestamp: bigint };
}

export interface CommitmentStorageInterface extends Interface {
  getFunction(
    nameOrSignature: "addCommitment" | "getCommitments"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CommitmentAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addCommitment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitments",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitments",
    data: BytesLike
  ): Result;
}

export namespace CommitmentAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    commitmentHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    commitmentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    commitmentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CommitmentStorage extends BaseContract {
  connect(runner?: ContractRunner | null): CommitmentStorage;
  waitForDeployment(): Promise<this>;

  interface: CommitmentStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCommitment: TypedContractMethod<
    [_commitmentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getCommitments: TypedContractMethod<
    [_user: AddressLike],
    [CommitmentStorage.CommitmentStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCommitment"
  ): TypedContractMethod<[_commitmentHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCommitments"
  ): TypedContractMethod<
    [_user: AddressLike],
    [CommitmentStorage.CommitmentStructOutput[]],
    "view"
  >;

  getEvent(
    key: "CommitmentAdded"
  ): TypedContractEvent<
    CommitmentAddedEvent.InputTuple,
    CommitmentAddedEvent.OutputTuple,
    CommitmentAddedEvent.OutputObject
  >;

  filters: {
    "CommitmentAdded(address,bytes32,uint256)": TypedContractEvent<
      CommitmentAddedEvent.InputTuple,
      CommitmentAddedEvent.OutputTuple,
      CommitmentAddedEvent.OutputObject
    >;
    CommitmentAdded: TypedContractEvent<
      CommitmentAddedEvent.InputTuple,
      CommitmentAddedEvent.OutputTuple,
      CommitmentAddedEvent.OutputObject
    >;
  };
}
