/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  CommitmentStorage,
  CommitmentStorageInterface,
} from "../CommitmentStorage";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "commitmentHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "CommitmentAdded",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_commitmentHash",
        type: "bytes32",
      },
    ],
    name: "addCommitment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "getCommitments",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "user",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "commitmentHash",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct CommitmentStorage.Commitment[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061029b8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80630522bf031461003b5780639f7ad1d114610064575b600080fd5b61004e6100493660046101b7565b610079565b60405161005b91906101e7565b60405180910390f35b61007761007236600461024c565b61010f565b005b6001600160a01b038116600090815260208181526040808320805482518185028101850190935280835260609492939192909184015b82821015610104576000848152602090819020604080516060810182526003860290920180546001600160a01b03168352600180820154848601526002909101549183019190915290835290920191016100af565b505050509050919050565b6040805160608101825233808252602080830185815242848601818152600085815280855287812080546001808201835591835291869020885160039093020180546001600160a01b0319166001600160a01b03909316929092178255935193810193909355516002909201919091559351938452919284927f76cfb50b011b627fb837419b42b9e75d3b2ecbf4f34887b9022cf3dbfe931eef910160405180910390a35050565b6000602082840312156101c957600080fd5b81356001600160a01b03811681146101e057600080fd5b9392505050565b602080825282518282018190526000918401906040840190835b8181101561024157835180516001600160a01b03168452602080820151818601526040918201519185019190915290930192606090920191600101610201565b509095945050505050565b60006020828403121561025e57600080fd5b503591905056fea2646970667358221220f298f3f7ea670732ab02318cf255f5a0d8964e382cee272f0900bf1ca9a7a72564736f6c634300081c0033";

type CommitmentStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CommitmentStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CommitmentStorage__factory extends ContractFactory {
  constructor(...args: CommitmentStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CommitmentStorage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CommitmentStorage__factory {
    return super.connect(runner) as CommitmentStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CommitmentStorageInterface {
    return new Interface(_abi) as CommitmentStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CommitmentStorage {
    return new Contract(address, _abi, runner) as unknown as CommitmentStorage;
  }
}
